Initial attempt at outline support
mathworks/MATLAB-language-server pull request #1
Opened 2023-05-05 20:25 UTC by rlivings39

Here's an initial attempt at outline support for https://github.com/mathworks/MATLAB-extension-for-vscode/issues/1

This has a few responsiveness bugs I need to investigate, so please don't actually merge yet. Still I wanted to get some initial feedback.

Some bits of feedback I'd like to hear about:

* Is this the right location? It feels navigation-related so I put it there. I could also imagine making a separate provider folder like `symbols` or `structure`.
* I've tried to integrate well with the MATLAB startup option. Editors make requests for document symbols very frequently so I chose to make the document symbol request not trigger a MATLAB start with `onDemand` as mentioned in my comment.
* One UX issue I didn't immediately see how to solve is: suppose you have A.m and foo.m open at VSCode launch. The documentSymbol request fires and since MATLAB hasn't started, we don't have any code index info yet. Right now I just return empty. It would be nice if I could wait on a promise or something for files to be indexed and then immediately return a response once the system is up and running. Any ideas on whether or not there's anything in the existing server that I could leverage for this?

Here's a screenshot of this in action:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/43882944/236561793-be8fdfe6-c275-4b46-85fb-d4e9bc34fb4f.png">

2023-05-09 14:11 UTC, dklilley commented on tsconfig.json
> +		"sourceMap": true,
Use spaces, not tabs

2023-05-09 14:17 UTC, dklilley commented on src/providers/navigation/NavigationSupportProvider.ts
>  function reportTelemetry (type: RequestType, errorCondition = '') {
I think this will need to be updated to handle the new RequestType being provided.

2023-05-09 14:43 UTC, dklilley commented on src/providers/navigation/NavigationSupportProvider.ts
> +            // TODO: When can this be null if we're in a classInfo case?
This can be null/undefined in edge cases, such as a function defined in an \@-folder but the classdef file is not present (or has not been indexed).

2023-05-09 17:43 UTC, dklilley commented
Can you also add an entry to the list in the README for document symbol support?

2023-05-10 03:44 UTC, zm-cttae commented
Does this work with mpm.m (multiple functions) and also a datastorage.m hugefile? Is there:

- variable assignment symbols
- anonymous function support etcetc

2023-05-10 11:29 UTC, rlivings39 commented on src/providers/navigation/NavigationSupportProvider.ts
> +            // TODO: When can this be null if we're in a classInfo case?
Got it. I need to handle this case and class folders in general better. Will fix that up.

2023-05-10 11:30 UTC, rlivings39 commented on tsconfig.json
> +		"sourceMap": true,
Fixed

2023-05-10 11:30 UTC, rlivings39 commented on src/providers/navigation/NavigationSupportProvider.ts
>  function reportTelemetry (type: RequestType, errorCondition = '') {
Fixed. Let me know what you think.

2023-05-10 11:30 UTC, rlivings39 commented
> Can you also add an entry to the list in the README for document symbol support?

Done

2023-05-12 14:40 UTC, rlivings39 commented
@zm-cttae Thanks for the feedback! Can you please point us to the paths for mpm.m and datastorage.m you have in mind and in what MATLAB release you're finding them? The versions I found in R2023a didn't seem right as mpm.m only had help comments.

Good design questions too. Those are good considerations for us for the future. Which block keywords did you have in mind?

2023-05-12 14:46 UTC, zm-cttae commented
Links to nice test cases:

- https://github.com/mobeets/mpm/blob/90a42c39365a1b508e9f143f1f562c89e14edeb1/mpm.m
- https://github.com/jgte/orb/blob/df184892563f22e449db85c8ebb09a9315c688f2/datastorage.m

To start with, the loops listed here: [*Loops and Conditional Statements - MATLAB & Simulink - MathWorks United Kingdom*](https://uk.mathworks.com/help/matlab/control-flow.html)

2023-05-12 14:59 UTC, rlivings39 commented
@zm-cttae Thanks! Those test cases seem to work well.

Noted on the request for loops, etc.

2023-05-12 16:11 UTC, dklilley requested changes

2023-05-12 16:11 UTC, dklilley commented on README.md
>  ### 1.0.0
Can you add an entry for this new version, and similarly update the value within package.json?

Since this is a new user-visible feature, I think this should be bumped to v1.1.0.

2023-05-12 16:11 UTC, dklilley commented on src/providers/navigation/NavigationSupportProvider.ts
> +            await Indexer.indexDocument(textDocument)
Do we need both `indexDocument` calls? Is there a situation where the first would result in codeData being null and we wouldn't want to default to the `return []` case?

2023-05-12 17:29 UTC, rlivings39 commented on README.md
>  ### 1.0.0
Done

2023-05-12 17:29 UTC, rlivings39 commented on src/providers/navigation/NavigationSupportProvider.ts
> +            await Indexer.indexDocument(textDocument)
Nope. Thanks for catching this.

2023-05-12 17:41 UTC, dklilley approved these changes

2023-05-12 17:41 UTC, merged