Resolve symlink of the `matlab` executable when finding install path
mathworks/MATLAB-language-server pull request #22
Opened 2023-10-20 11:26 UTC by MoetaYuko

2023-10-25 17:48 UTC, dklilley requested changes
Thanks for looking into this!

2023-10-25 17:48 UTC, dklilley commented on src/providers/linting/LintingSupportProvider.ts
> +import fs = require('fs')
Please use `import * as fs from 'fs'` syntax instead

2023-10-25 17:48 UTC, dklilley commented on src/providers/linting/LintingSupportProvider.ts
> +                        }
If there is an error, it would be good to log it using `Logger`

2023-10-27 18:17 UTC, nothans commented
Can you contact me to sign a CLA? Thank you for the PR!

2023-11-01 16:32 UTC, nothans commented
The CLA has been signed. Please evaluate the PR. Thank you for the contribution!

2023-11-01 20:48 UTC, dklilley commented
Hi @MoetaYuko, I am trying this out but I think this is not behaving as desired. When I try this, I am seeing that line 356 is executed before the `fs.realpath` callback is executed, resulting in a null return every time.

Is this what you are seeing as well?

2023-11-02 02:40 UTC, MoetaYuko commented
> Hi @MoetaYuko, I am trying this out but I think this is not behaving as desired. When I try this, I am seeing that line 356 is executed before the `fs.realpath` callback is executed, resulting in a null return every time.
> 
> Is this what you are seeing as well?

Nope, it simply works as expected on my side.
* I didn't manually set matlabInstallPath so that the "else" block on line 338 is entered, then the "try" block.
* I have a symlink `/usr/bin/matlab -> /opt/MATLAB/R2023a/bin/matlab` where `/usr/bin` is in $PATH obviously. Before this PR `binPath` was assigned `/usr/bin`, but now it's `/opt/MATLAB/R2023a/bin` which is expected.

2023-11-02 14:05 UTC, dklilley commented
I think this may be working for you somewhat by luck. Since you are using the non-promise version of `fs.realpath`, I don't believe the `await` has any effect. If it resolves fast enough, the callback function may be executed before the `try` is exited, however this is not guaranteed.

2023-11-03 15:30 UTC, MoetaYuko commented
> I think this may be working for you somewhat by luck. Since you are using the non-promise version of `fs.realpath`, I don't believe the `await` has any effect. If it resolves fast enough, the callback function may be executed before the `try` is exited, however this is not guaranteed.

Indeed. You reminded me that `async` shouldn't be used. Now I switched to the promise version so it should be working.

2023-11-03 17:58 UTC, dklilley commented
Thanks for making that change!

For me, `realpath` is resolving to `/usr/local/MATLAB/R2023b/bin/matlab`, which is expected. However, for this to work, I believe that `binPath` needs to point to `/usr/local/MATLAB/R2023b/bin/`.

2023-11-04 04:27 UTC, MoetaYuko commented
Oops, my bad, this revision must be okay...

2023-11-06 14:47 UTC, merged